"""empty message

Revision ID: 3b94493cdffd
Revises: 9fbc2548c658
Create Date: 2022-08-01 19:08:36.389334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b94493cdffd'
down_revision = '9fbc2548c658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genres_genre_id_fkey', 'venue_genres', type_='foreignkey')
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'venue_genres', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key('venue_genres_genre_id_fkey', 'venue_genres', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
