"""empty message

Revision ID: 97faa63f2c83
Revises: e38a32db3853
Create Date: 2022-08-01 23:09:43.691107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97faa63f2c83'
down_revision = 'e38a32db3853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'artist', ['image_link'])
    op.create_unique_constraint(None, 'artist', ['name'])
    op.create_unique_constraint(None, 'artist', ['facebook_link'])
    op.create_unique_constraint(None, 'artist', ['website'])
    op.create_unique_constraint(None, 'artist', ['phone'])
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(None, 'venue', ['phone'])
    op.create_unique_constraint(None, 'venue', ['image_link'])
    op.create_unique_constraint(None, 'venue', ['facebook_link'])
    op.create_unique_constraint(None, 'venue', ['website'])
    op.create_unique_constraint(None, 'venue', ['name'])
    op.create_unique_constraint(None, 'venue', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'venue', type_='unique')
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
