"""empty message

Revision ID: e38a32db3853
Revises: 668fdd935046
Create Date: 2022-08-01 19:50:25.357125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38a32db3853'
down_revision = '668fdd935046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genres_genre_id_fkey', 'artist_genres', type_='foreignkey')
    op.drop_constraint('artist_genres_artist_id_fkey', 'artist_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genres', 'artist', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artist_genres', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    op.create_foreign_key('artist_genres_artist_id_fkey', 'artist_genres', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key('artist_genres_genre_id_fkey', 'artist_genres', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
